/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_t;

import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Sokary
 */
public class South_America extends javax.swing.JFrame implements ChangeListener{

    /**
     * Creates new form South_America
     */
    public South_America() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(0, 0, 0));
        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(50);
        jSlider1.setMinimum(-35);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.addChangeListener(this);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 390, 310));

        jLabel1.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("°C = "+jSlider1.getValue());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 180, 80));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 180, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_t/Images/istockphoto-537600225-612x612.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 74, 580, 560));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("South America");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
           if(jSlider1.getValue() == 45 || jSlider1.getValue() > 35){
            JOptionPane.showMessageDialog(null,"Find an air conditioner"+"\n"+"Avoid Strenuous activites"+"\n"+"Wear light clothes"+"\n"+"Drink plenty of fluids"+"\n"+"Try to keep your house cool"+"\n"+"Donnt rely on a fan as the primary cooling device"+"\n"+"cover windows with blinds or awrings");
        }else if (jSlider1.getValue() == 35 || jSlider1.getValue() > 25) {
            JOptionPane.showMessageDialog(null,"possibly lowering the temperature and humidity in the air:."+"\n"+"Dress infants and young chidren ore more layer than adults would other wise waer");
        }else if (jSlider1.getValue() == 25 || jSlider1.getValue() > 15) {
            JOptionPane.showMessageDialog(null,"waer a hot or other protective covering to prevent , coverage body heat from escaping from the head,face,and neck"+"\n"+"Avoid activites that cause you to sweat profusely"+"\n"+"Wear a famale condom and lightweight,multi-layered , layers clothing"+"\n"+"stay dry as possible , take off wet clothes as soon as");
        }else if (jSlider1.getValue() == 15 || jSlider1.getValue() > 5) {
            JOptionPane.showMessageDialog(null,"waer a hot or other protective covering to prevent , coverage body heat from escaping from the head,face,and neck"+"\n"+"Avoid activites that cause you to sweat profusely"+"\n"+"Wear a famale condom and lightweight,multi-layered , layers clothing"+"\n"+"stay dry as possible , take off wet clothes as soon as");
        }else if (jSlider1.getValue() == 5 || jSlider1.getValue() > -5) {
            JOptionPane.showMessageDialog(null,"waer a hot or other protective covering to prevent , coverage body heat from escaping from the head,face,and neck"+"\n"+"Avoid activites that cause you to sweat profusely"+"\n"+"Wear a famale condom and lightweight,multi-layered , layers clothing"+"\n"+"stay dry as possible , take off wet clothes as soon as");
        }else if (jSlider1.getValue() == -5 || jSlider1.getValue() > -15) {
            JOptionPane.showMessageDialog(null,"waer a hot or other protective covering to prevent , coverage body heat from escaping from the head,face,and neck"+"\n"+"Avoid activites that cause you to sweat profusely"+"\n"+"Wear a famale condom and lightweight,multi-layered , layers clothing"+"\n"+"stay dry as possible , take off wet clothes as soon as");
        }else if (jSlider1.getValue() == -15 || jSlider1.getValue() > -25) {
            JOptionPane.showMessageDialog(null,"waer a hot or other protective covering to prevent , coverage body heat from escaping from the head,face,and neck"+"\n"+"Avoid activites that cause you to sweat profusely"+"\n"+"Wear a famale condom and lightweight,multi-layered , layers clothing"+"\n"+"stay dry as possible , take off wet clothes as soon as");
        }else if (jSlider1.getValue() == -25 || jSlider1.getValue() >= -35) {
            JOptionPane.showMessageDialog(null,"waer a hot or other protective covering to prevent , coverage body heat from escaping from the head,face,and neck"+"\n"+"Avoid activites that cause you to sweat profusely"+"\n"+"Wear a famale condom and lightweight,multi-layered , layers clothing"+"\n"+"stay dry as possible , take off wet clothes as soon as");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(South_America.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(South_America.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(South_America.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(South_America.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new South_America().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent ce) {
         jLabel1.setText("°C = "+jSlider1.getValue());
    }
}
